### ISSUE TITLE
 frame_data_list = data.get("frames") if data else None

### ISSUE THREAD

**Issue by xiayangqun** [justbilt/untp#11]
there is something wrong when i use these tool ,

`Traceback (most recent call last):
  File "./untp.py", line 125, in <module>
    main()
  File "./untp.py", line 122, in main
    return unpacker(argument.path, image_file = argument.image_file, output_dir = argument.output)
  File "./untp.py", line 46, in unpacker
    frame_data_list = data.get("frames") if data else None
AttributeError: 'list' object has no attribute 'get'
xiayangqundeMacBook-Pro:untp xiayangqun$ ./untp.py /Users/xiayangqun/Documents/PersonWorkSpace/AppleDeveloper/zombieKiller/OriginalRes/ui/shop.plist
input /Users/xiayangqun/Documents/PersonWorkSpace/AppleDeveloper/zombieKiller/OriginalRes/ui/shop.plist
Traceback (most recent call last):
  File "./untp.py", line 125, in <module>
    main()
  File "./untp.py", line 122, in main
    return unpacker(argument.path, image_file = argument.image_file, output_dir = argument.output)
  File "./untp.py", line 46, in unpacker
    frame_data_list = data.get("frames") if data else None
AttributeError: 'list' object has no attribute 'get'`

**Comment by justbilt** [comment]
Could you provide your `untp version` and `shop.plist`, `shop.png` content ?

**Comment by xiayangqun** [comment]
finally I find the error location is in dataparse.py in line 145
it shuold 
`return data`
but your code is return wrong things

**Comment by justbilt** [comment]
Yes, you are right , i fixed it in 1.0.7, you could use `pip install -U untp` upgrade to latest version.

This really is low-level mistake, i will add test case to this project and make sure it crossed test before a new version upload.

Thank you.
