### ISSUE TITLE
报错：TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Ray1024** [justbilt/untp#12]
有的plist文件会报错如下，请问为什么呀：
C:\Users\Administrator\Desktop\uuu>untp FishActor-Marlin.plist
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\untp.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\untp\untp.py", line 121, in main
    return unpacker(argument.path, image_file = argument.image_file, output_dir = argument.output)
  File "c:\python27\lib\site-packages\untp\untp.py", line 44, in unpacker
    data = dataparse.parse_file(data_file, config, extra_data_receiver)
  File "c:\python27\lib\site-packages\untp\dataparse.py", line 20, in parse_file
    return parse_plistdata(data)
  File "c:\python27\lib\site-packages\untp\dataparse.py", line 106, in parse_plistdata
    frame["x"],
TypeError: 'NoneType' object has no attribute '__getitem__'
![tim 20170721151359](https://user-images.githubusercontent.com/20392447/28452900-4447bc5c-6e27-11e7-8454-8ad94025a775.png)

**Comment by justbilt** [comment]
可否提供下 untp 的版本, 可以通过获取 `pip show untp`; 如果版本低于 1.0.7 的话, 可以先尝试升级, 使用 `pip install -U untp` 来升级.

如果还是不行的话, 请提供下出错的 plist 及图片.

**Comment by Ray1024** [comment]
我上周五刚装的，是最新的版本：

就是个别plist文件会报错，你帮忙看看。

（PS：plist文件在附件）

非常感谢！



guojianlei010@163.com
 
发件人： justbilt
发送时间： 2017-07-22 08:13
收件人： justbilt/untp
抄送： Jianlei Guo; Author
主题： Re: [justbilt/untp] 报错：TypeError: 'NoneType' object has no attribute '__getitem__' (#12)
可否提供下 untp 的版本, 可以通过获取 pip show untp; 如果版本低于 1.0.7 的话, 可以先尝试升级, 使用 pip install -U untp 来升级.
如果还是不行的, 可以提供下对应的 plist 及图片.

**Comment by justbilt** [comment]
非常抱歉, 我在邮箱中没有找到附件, 麻烦重新提供下, 可以直接邮件到我的邮箱:
justbilt@qq.com

我观察了下错误堆栈, 应该是 plist 中解析 `frame` 字段时的格式错误.
麻烦在提供 plist 的同时吧图片也带上, 只有 plist 是无法解析成功的.

**Comment by justbilt** [comment]
已经修复了这个bug, 我上传了新的版本 1.0.9, 您可以通过:

```
pip install -U untp
```

来升级安装, 如果还有什么问题, 欢迎反馈.

**Comment by Ray1024** [comment]
问题解决了，非常感谢！
