### ISSUE TITLE
Can't convert pvr.ccz with content protection to png

### ISSUE THREAD

**Issue by chongchaoyu** [justbilt/untp#16]
If the pvr.ccz has been protected with a key, untp can't convert it to png successfully.
And I check the untp sources and the usage of TexturePacker, it has a "--content-protection" option, but this option looks like for encrypting the pvr.ccz, other than decryption.

Do you have some idea? Thank you!

**Comment by justbilt** [comment]
Sorry for later, i think it's an good idea.

TexturePacker does not provide decryption option, we should implement it by ourself. Fortunately, the decrypt arithmetic is very simple, just xor ever bit with key. We could ref cocos implementation:

https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/ZipUtils.cpp#L58

I'm interested in it, i'll implement it soon.

**Comment by chongchaoyu** [comment]
I am looking forward to it, thank you very much!

**Comment by justbilt** [comment]
Sorry for later, this feature has been published at 1.1.6, hope u will enjoy it !

**Comment by chongchaoyu** [comment]
thank u, I will try it later！发自我的华为手机-------- 原始邮件 --------主题：Re: [justbilt/untp] Can't convert pvr.ccz with content protection to png (#16)发件人：justbilt 收件人：justbilt/untp 抄送：chongchaoyu ,Author Sorry for later, this feature has been published at 1.1.6, hope u will enjoy it !

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/justbilt/untp","title":"justbilt/untp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/justbilt/untp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@justbilt in #16: Sorry for later, this feature has been published at 1.1.6, hope u will enjoy it !"}],"action":{"name":"View Issue","url":"https://github.com/justbilt/untp/issues/16#issuecomment-402960287"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/justbilt/untp/issues/16#issuecomment-402960287",
"url": "https://github.com/justbilt/untp/issues/16#issuecomment-402960287",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [justbilt/untp] Can't convert pvr.ccz with content protection to png (#16)",
"sections": [
{
"text": "",
"activityTitle": "**justbilt**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@justbilt",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"justbilt/untp\",\n\"issueId\": 16,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"justbilt/untp\",\n\"issueId\": 16\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/justbilt/untp/issues/16#issuecomment-402960287"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339730724\n}"
}
],
"themeColor": "26292E"
}
]
