### ISSUE TITLE
Untp can't unpack pngs with transparent pixels

### ISSUE THREAD

**Issue by chongchaoyu** [justbilt/untp#17]
Thank you first for this tool, and I find there is another issue:)

If the pvr.ccz has transparent pixels, after unpacking, all the pngs' transparent pixels are missing.
I will send the plist and png files to your email(wangbilt@gmail.com;).

**Comment by justbilt** [comment]
I have been tested with your attached files, and i think the result is correct. 

The output file `b_main_bg__1.png` has alpha piexls area, so could you tell me about you untp version and TexturePacker version ?

I think maybe your TexturePacker doesn't recognize `--no-trim` options when convert pvr to png.

My test result file:
[b_main_bg__1.png.zip](https://github.com/justbilt/untp/files/2115864/b_main_bg__1.png.zip)

My env:
untp: 1.1.5
TexturePacker: 3.1.2

**Comment by chongchaoyu** [comment]
Thank you:)
