### ISSUE TITLE
not support pvr

### ISSUE THREAD

**Issue by ghost** [justbilt/untp#2]
```
Traceback (most recent call last):
  File "src/untp.py", line 72, in <module>
    main()
  File "src/untp.py", line 69, in main
    return unpacker(plist_file, image_file)
  File "src/untp.py", line 14, in unpacker
    except (Exception, e):
NameError: global name 'e' is not defined
```

**Comment by justbilt** [comment]
thanks your feedback, this bug really exists.

but there no good idear to solved this problem, beacuse the most image parse llibrary unsupported pvr format . 

one way is use  TextturePacker command line tools convert pvr to png, than do unpack same as png file, so you must ensure installed TextturePacker .

i will fix it after i finished my travel, 

so if you are imperative , you could use a shell to batch convert pvr to png [http://gamedev.stackexchange.com/questions/11801/batch-conversion-of-pvr-to-jpeg-or-similar](http://gamedev.stackexchange.com/questions/11801/batch-conversion-of-pvr-to-jpeg-or-similar) and call untp with second param:

```
unpy xxx.plist xxx.png
```

**Comment by ghost** [comment]
哈哈，过春节。

**Comment by justbilt** [comment]
哈哈, 确实如此 !
