### ISSUE TITLE
建议可以忽略plist里面找不到的文件.

### ISSUE THREAD

**Issue by w1ng** [justbilt/untp#6]
维护一些年代久远的项目的时候,
发现plist和png有点对不上
各种报No such file or directory:'xxxx.png'的错误
可不可以直接忽略这类错误,只处理plist里能找到的图片.
在plist里面一个个对照着删略繁琐....

**Comment by justbilt** [comment]
感谢, 非常有用的建议, 已经在 1.0.4 版修复. 使用

```
pip install -U untp
```

安装更新
